### ISSUE TITLE
Integration of the THI News Feed

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#86]
Heya, Maybe include a THI Newsfeed-Page?

Or even improve it with the news from the faculty the person is in. 

eg. you are in faculty I and want to keep updated on these news.
Please make it editable so you can show more than only your own facultys news

**Comment by M4GNV5** [comment]
The THI news embedded in the original App are sourced from https://www.thi.de/hochschule/aktuelles/presse and available in the App API via [`thiwebinfo`](https://github.com/neuland-ingolstadt/THI-App/blob/develop/thi-rest-api.md#news).

Issue #7 already tracks re-implementing the news API endpoint, which is easy since we already re-implemented the calender / THI-events functionality, however to be honest i see no use of news in the Neuland App

**Comment by M4GNV5** [comment]
To be honest most students probably do not care about the press statements released by the THI, thus we probably will not work on this in the near future or at all. I will close this issue for now, but we are open to a pull request implementing this feature from someone who thinks this more important than i do.
