### ISSUE TITLE
Make the SPO and module handbooks recognisable and link the PDF files.

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#90]
Since it is a (not working)function of the original App to view your SPO.

Maybe we could try and include a Download to SPO as well as module handbooks somewhere in the App. 

(Maybe a My Area Space?)

**Comment by M4GNV5** [comment]
In theory the `persdata` API call returns a link to the SPO. We already use this link in https://dev.neuland.app/personal where you can click on your SPO version.

For me however this link returns a 404:
https://www.thi.de/hochschule/ueber-uns/verwaltung-und-stabsstellen/stabsstelle-recht/satzungen-fakultaet-elektrotechnik-und-informatik/masterstudiengaenge/master-applied-research/

I assume they reorganized their website, replacing `verwaltung-und-stabsstellen` with `hochschulorganisation` results in a working link:
https://www.thi.de/hochschule/ueber-uns/hochschulorganisation/stabsstelle-recht/satzungen-fakultaet-elektrotechnik-und-informatik/masterstudiengaenge/master-applied-research/

So in order to fix this issue we simply have to add a hack that fixes the URL?

**Comment by FabianSimonGross** [comment]
Yes that hack might be valuable.

But otherwise it's a bit of a pain to look for the module handbooks they are usually avalible on the web but. sometimes on moodle.

Maybe at least scrape this? 
![Bildschirmfoto vom 2021-09-22 12-22-23](https://user-images.githubusercontent.com/81598210/134327074-99c69dcd-6016-400a-a700-ed1557f5fddc.png)
